name: demo_plugin_example
description: Demonstrates how to use the demo_plugin plugin.
publish_to: 'none'
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  demo_plugin:
    path: ../
flutter:
  uses-material-design: true